version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - migrations
    environment:
      POSTGRES_DB: trading_simulator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: db
      API_HOST: 3000.ymaril.dev
    env_file:
      - secrets.env
  db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: trading_simulator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./tmp:/mnt/doc_mnt
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rake db:migrate
    depends_on:
      - db
    restart: on-failure:5
    environment:
      POSTGRES_DB: trading_simulator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: db